#!/usr/bin/env bash
set -euo pipefail

# P1-02 cleanup: only resources bearing the exact byte-p1-02 names and images
# that were absent before this qualification pass are eligible for removal.

export DOCKER_HOST="unix://$HOME/.docker/run/docker.sock"

project_name="byte-p1-02"
project_root="$HOME/.byte-p1-02-qual"
persist_name="${project_name}-persist"
web_name="${project_name}-web"
smoke_name="${project_name}-smoke"
alpine_image="alpine:3.20"
web_image="traefik/whoami:latest"

pre_alpine=yes
pre_web=yes
if [[ -f "$project_root/pre_images.env" ]]; then
  # File is generated by the qualification task and contains only yes/no values.
  # shellcheck disable=SC1090
  source "$project_root/pre_images.env"
fi

if [[ -f "$project_root/compose.yaml" ]]; then
  docker compose -p "$project_name" -f "$project_root/compose.yaml" down --remove-orphans >/dev/null 2>&1 || true
fi

docker rm -f "$smoke_name" "$persist_name" "$web_name" >/dev/null 2>&1 || true

image_cleanup_alpine=preserved_preexisting
if [[ "$pre_alpine" == "no" ]]; then
  if docker image rm "$alpine_image" >/dev/null 2>&1; then
    image_cleanup_alpine=removed
  else
    image_cleanup_alpine=retained_in_use_or_already_absent
  fi
fi

image_cleanup_whoami=preserved_preexisting
if [[ "$pre_web" == "no" ]]; then
  if docker image rm "$web_image" >/dev/null 2>&1; then
    image_cleanup_whoami=removed
  else
    image_cleanup_whoami=retained_in_use_or_already_absent
  fi
fi

rm -rf "$project_root"

leftovers=$(docker ps -a --format '{{.Names}}' | grep -E '^byte-p1-02-(smoke|persist|web)$' || true)
if [[ -n "$leftovers" ]]; then
  echo 'temporary_container_cleanup=fail' >&2
  exit 1
fi
if [[ -e "$project_root" ]]; then
  echo 'temporary_bind_data_cleanup=fail' >&2
  exit 1
fi

printf 'image_cleanup_alpine=%s\n' "$image_cleanup_alpine"
printf 'image_cleanup_whoami=%s\n' "$image_cleanup_whoami"
echo 'temporary_container_cleanup=pass'
echo 'temporary_bind_data_cleanup=pass'
echo 'docker_system_df_after_cleanup_begin'
docker system df
echo 'docker_system_df_after_cleanup_end'
echo 'cleanup=pass'
